print("hello \"world\" world")
print('hello I\'m kazimuddin')
print("line A\nline B")
print("line A\nline B\nline C")
print("name\tkazimuddin")
print("this is blackslash\ ")
print("this is blackslash\\")
print("this is blackslash\\\\")
print("hell\blo")
print("kazim\bmuddin")